"""
vision_config.py
================
Central configuration for the VoiceChess vision (camera) subsystem.

All tuneable constants for image capture, calibration, detection, and
diagnostics live here. Edit this file without touching any logic modules.

Layout
------
    Oficinas/
        voice/          ← voice command system
        vision/         ← this module
        vision_config.py
"""

from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

VISION_DIR   = Path(__file__).parent.resolve()          # Oficinas/vision/
OFICINAS_DIR = Path(__file__).parent.parent.resolve()   # Oficinas/

# Generated by vision/scripts/calibrate_camera.py; read at runtime
CALIBRATION_FILE: str = str(VISION_DIR / "camera_calibration.json")

# Diagnostic images directory (inside vision/)
DIAGNOSTIC_DIR: str = str(VISION_DIR / "diags")

# ---------------------------------------------------------------------------
# Camera capture
# ---------------------------------------------------------------------------

# OpenCV VideoCapture device index (0 = first USB/webcam on the system)
CAMERA_DEVICE_INDEX: int = 0

# Capture resolution (width, height).
# Lower = faster on Pi 3B+; higher = better detail for piece detection.
CAMERA_RESOLUTION: tuple[int, int] = (1280, 960)

# Seconds to wait after opening the camera before the first capture.
# Allows auto-exposure and auto-focus to stabilise.
CAMERA_WARMUP_SECONDS: float = 2.0

# ---------------------------------------------------------------------------
# Perspective correction
# ---------------------------------------------------------------------------

# Size (pixels) of the corrected top-down board image (square).
# 640 → 80 px per square —# Output dimensions for the perspective-corrected image
BOARD_OUTPUT_SIZE_PX: int = 640

# Width of the cemetery regions on the left and right of the board.
# Based on physical schematic: Board = 48cm, Cemetery+Gap = 20cm
# 640 * (20 / 48) = 266.66px
CEMETERY_REGION_WIDTH_PX: int = 267

# Number of cemetery slots per side (usually 8, matching board rows)
CEMETERY_SLOTS_PER_SIDE: int = 8

# ---------------------------------------------------------------------------
# Occupancy detection
# ---------------------------------------------------------------------------

# Minimum mean absolute pixel difference (0–255 normalised to 0.0–1.0)
# between a square in the reference (empty) image and the current image
# for the square to be considered occupied.
OCCUPIED_DIFF_THRESHOLD: float = 0.12

# Minimum pixel variance within a ROI for "occupied" classification.
# Very uniform squares (low variance) are likely empty dark/light wood.
OCCUPIED_VARIANCE_THRESHOLD: float = 180.0

# ---------------------------------------------------------------------------
# Color detection
# ---------------------------------------------------------------------------

# HSV brightness threshold: squares brighter than this are "white" pieces.
# Range 0–255.
PIECE_BRIGHTNESS_THRESHOLD: int = 160

# Minimum saturation for a pixel to be considered "coloured" (not neutral).
# Helps ignore board texture when classifying piece colour.
PIECE_SATURATION_MIN: int = 30

# ---------------------------------------------------------------------------
# Quality / confidence
# ---------------------------------------------------------------------------

# Minimum confidence score [0.0–1.0] to accept a board state as valid.
# Results below this trigger a retry.
MIN_CONFIDENCE: float = 0.70

# Maximum capture + processing attempts before returning CAPTURE_FAILED.
MAX_CAPTURE_ATTEMPTS: int = 3

# Seconds to wait between retry attempts.
RETRY_DELAY_SECONDS: float = 1.5

# ---------------------------------------------------------------------------
# Gantry synchronisation (stubbed — not used in test phase)
# ---------------------------------------------------------------------------

# Seconds to wait after gantry signals "move complete" before capturing,
# allowing the structure to stop vibrating.
POST_MOVE_SETTLE_SECONDS: float = 1.5

# ---------------------------------------------------------------------------
# Diagnostic image storage
# ---------------------------------------------------------------------------

# Set to True during development to save captured and processed images.
# Set to False in production to avoid filling the SD card.
SAVE_DIAGNOSTIC_IMAGES: bool = True

# Maximum number of diagnostic files to keep before rotating (oldest deleted).
MAX_DIAGNOSTIC_FILES: int = 100

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

# Mirrors the voice system's logging constants so both subsystems share style.
LOG_LEVEL: str  = "INFO"
LOG_FORMAT: str = "[%(asctime)s] %(levelname)-8s %(name)s - %(message)s"
LOG_DATE_FORMAT: str = "%H:%M:%S"
